version: img-only-v1.2
categories:
  # =========================
  # 通用安全（现场行为/环境类）
  # =========================
  高处/临边防护(安全):
    kind: safety
    labels: [临边无防护栏, 仅一道栏杆, 无踢脚板, 洞口未覆盖, 洞口覆盖无固定, 安全带未系挂, 临时通道无防护]
    synonyms: [临边, 坠落, 护栏, 栏杆, 踢脚板, 洞口, 孔洞, 高处作业, 安全带, 生命绳, 防坠器]
  脚手架/作业平台(安全):
    kind: safety
    labels: [连墙件缺失, 扣件松动, 斜撑缺失, 脚手板离缝, 外侧未设挡脚板, 超载堆料, 未经验收挂牌]
    synonyms: [脚手, 盘扣, 碗扣, 门式, 连墙, 立杆, 横杆, 剪刀撑, 作业平台]
  起重吊装/机械(安全):
    kind: safety
    labels: [无警戒区, 指挥不到位, 起吊超载可疑, 吊索具报废标准不符, 回转半径内站人, 立体交叉作业未隔离]
    synonyms: [吊装, 起重, 吊钩, 钢丝绳, 卡环, 吊点, 天车, 塔吊, 指挥信号]
  临时用电/电气(安全):
    kind: safety
    labels: [配电箱门未闭锁, 漏电保护器缺失或失效, 电缆裸露, 乱拉乱接, 一闸多机, 接地接零不规范]
    synonyms: [临电, 漏保, 配电箱, 开关箱, 电缆, 保护接地, TN, TT, 三级配电]
  动火作业/消防(安全):
    kind: safety
    labels: [动火无审批, 现场无灭火器, 易燃物未清理, 气瓶混放无隔离, 软管老化, 未配防回火装置]
    synonyms: [氧气瓶, 乙炔, 焊割, 明火, 动火票, 灭火器, 消防栓, 防火毯]
  挖掘/深基坑/受限空间(安全):
    kind: safety
    labels: [边坡防护缺失, 基坑围挡失效, 排水不畅涌水, 支护变形, 受限空间未检测, 未设置监护人]
    synonyms: [基坑, 边坡, 土方, 坑槽, 钢支撑, 护筒, 受限空间, 气体检测, 通风, 监护]
  交通与车辆(安全):
    kind: safety
    labels: [人车未分离, 逆行, 无限速标识, 倒车无指挥, 临边行车, 叉车无警示灯]
    synonyms: [交通, 叉车, 自卸车, 倒车, 车行道, 隔离, 限速]
  PPE个体防护(安全):
    kind: safety
    labels: [未戴安全帽, 帽带未系, 未穿反光背心, 未戴护目镜, 未戴防护手套, 未穿防砸鞋]
    synonyms: [个人防护, 劳保, 安全帽, 护目, 手套, 反光衣, 防砸]
  现场5S与环境(安全):
    kind: safety
    labels: [通道堵塞, 杂物堆放, 照明不足, 临边警示缺失, 未设警戒线, 雨天防滑处理不足]
    synonyms: [5S, 现场管理, 通道, 警示, 照度, 积水, 防滑]
  危险化学品/环保(安全):
    kind: safety
    labels: [危化品未标识, 储存混放, 泄漏未处置, 粉尘控制不足, 噪声超标, 废料未分类]
    synonyms: [化学品, SDS, 粉尘, 噪声, VOC, 泄漏, 危废, 分类收集]

  # =========================
  # 主体结构（安全+质量）
  # =========================
  模板支架/临时支撑(结构-安全):
    kind: safety
    labels: [模板支撑未闭合体系, 立杆沉降, 扣件松动, 超高支模未专项方案, 拆模未达强度]
    synonyms: [模板, 支撑体系, 支模, 扣件, 盘扣, 临时支撑, 拆模, 强度龄期]
  钢筋工程(结构-质量):
    kind: quality
    labels: [钢筋规格错误, 加密区漏设, 保护层不足, 搭接长度不足, 箍筋间距超差, 锚固长度不足]
    synonyms: [钢筋, 保护层, 搭接, 锚固, 箍筋, 加密, 植筋, 套筒]
  混凝土浇筑与成型(结构-质量):
    kind: quality
    labels: [蜂窝麻面, 露筋, 冷缝, 振捣不密实, 回弹/强度不足可疑, 分层不当, 养护不足]
    synonyms: [混凝土, 浇筑, 养护, 强度, 回弹, 冷缝, 麻面, 振捣]
  预应力/装配式(结构-质量):
    kind: quality
    labels: [锚具安装不规范, 孔道压浆不饱满, 张拉记录缺失, 构件吊装缝未灌浆, 干式连接未锁定]
    synonyms: [预应力, 张拉, 压浆, 锚具, 波纹管, 装配式, 灌浆料]
  砌体与围护(结构-质量):
    kind: quality
    labels: [砂浆饱满度不足, 组砌不规范, 构造柱拉结筋缺失, 皮数杆控制不准, 墙体开裂]
    synonyms: [砌体, 砖, 砌筑, 构造柱, 拉结筋, 砂浆, 饱满度]
  钢结构/连接(结构-安全+质量):
    kind: both
    labels: [高强螺栓未终拧或漏装, 焊缝未探伤或缺陷, 构件变形, 防腐涂装不合格]
    synonyms: [钢结构, 焊接, 螺栓, 高强螺栓, 超声, 磁粉, 涂装, 防腐]

  # =========================
  # 给排水/消防（安全+质量）
  # =========================
  给水与管材安装(给排水-质量):
    kind: quality
    labels: [管材型号错误, 走向不直顺, 支吊架间距超差, 套管/防水翼环缺失, 管道坡度错误]
    synonyms: [给水, 冷热水, PPR, 不锈钢, 镀锌, 支吊架, 套管, 坡度]
  排水与水封(给排水-质量):
    kind: quality
    labels: [存水弯缺失, 排水倒坡, 检修口缺失, 接口渗漏, 隔油池构造错误]
    synonyms: [排水, 水封, 地漏, 存水弯, 立管, 横管, 伸缩节]
  消防给水/喷淋(消防-安全+质量):
    kind: both
    labels: [喷头遮挡或间距不合格, 管网试压/冲洗不合格, 消火栓布置不合理, 末端试水未设置]
    synonyms: [消防, 喷淋, 消火栓, 末端试水, 试压, 冲洗, 报警阀]
  泵房与设备(给排水-质量):
    kind: quality
    labels: [基础标高偏差, 减震/隔振缺失, 接口柔性连接缺失, 标识不全, 设备就位偏差]
    synonyms: [泵房, 水泵, 膨胀罐, 隔振, 基础, 联轴器, 对中]

  # =========================
  # 机电安装（强电/弱电/HVAC/电梯等）
  # =========================
  电气强电配电(机电-安全+质量):
    kind: both
    labels: [配电箱回路标识缺失, 母线槽接头未紧固, 电缆桥架无跨接接地, 端接压接不规范, 绝缘电阻不合格]
    synonyms: [强电, 配电, 低压柜, 母线槽, 桥架, 端接, 压接, 绝缘, 接地]
  照明/应急疏散(机电-安全):
    kind: safety
    labels: [应急照明未联动, 疏散指示方向错误, 灯具安装高度不符, 防爆区域灯具错误]
    synonyms: [照明, 应急, 疏散, 指示, 联动, 防爆]
  弱电与系统集成(机电-质量):
    kind: quality
    labels: [线缆未分色或编带, 终端标签缺失, 线槽满载率超标, 机柜理线不规范, 系统联调缺陷]
    synonyms: [弱电, 综合布线, 安防, 门禁, BMS, 机柜, 理线, 编带]
  接地与防雷(机电-安全):
    kind: safety
    labels: [接地电阻超标, 等电位连接缺失, 避雷引下线断开, 桥架/设备未跨接]
    synonyms: [接地, 防雷, 等电位, 接地电阻, 跨接, 引下线]
  HVAC风管/水系统(机电-质量):
    kind: quality
    labels: [风管法兰密封不良, 玻纤保温破损, 水系统坡度与排气不良, 阀门方向错误, 压力试验不合格]
    synonyms: [暖通, 风管, 保温, 风口, 水系统, 阀门, 压差, 试压, 平衡]
  电梯与特种设备(机电-安全+质量):
    kind: both
    labels: [井道防护缺失, 层门孔洞未封, 吊装未设专用工装, 报验资料缺失, 制动/限速器联调不合格]
    synonyms: [电梯, 井道, 层门, 吊装, 试验, 报检, 制动器, 限速器]

  # =========================
  # 地基与基础（安全+质量）
  # =========================
  基坑支护与降水(基础-安全):
    kind: safety
    labels: [支护体系未闭合, 立柱/内支撑失稳, 围檩位移超限, 降水不足涌水, 坑边超载堆土]
    synonyms: [基坑, 支护, 内支撑, 钢支撑, 围檩, 止水帷幕, 降水, 监测]
  桩基础/地基处理(基础-质量):
    kind: quality
    labels: [桩位偏差, 桩顶标高错误, 桩身缺陷可疑, 灌注记录缺失, 复合地基加固不达标]
    synonyms: [桩, 钻孔灌注桩, CFG桩, 预制桩, 低应变, 静载, 复合地基, 加固]
  承台/垫层/防水(基础-质量):
    kind: quality
    labels: [垫层厚度不足, 防水节点收头不规范, 止水带错位, 保护层破坏, 回填压实度不足]
    synonyms: [承台, 垫层, 基础梁, 防水, 止水带, 收头, 回填, 压实]
  土方开挖与回填(基础-安全+质量):
    kind: both
    labels: [放坡不足, 临边无防护, 回填分层厚度超标, 密实度不合格, 施工道路软基未处理]
    synonyms: [土方, 开挖, 放坡, 回填, 密实度, 临边, 施工便道]

  # =========================
  # 建筑装饰/防水/成品（质量为主）
  # =========================
  砼与砂浆通病(质量通用):
    kind: quality
    labels: [开裂, 渗漏, 空鼓, 蜂窝麻面, 露筋, 表面起砂, 缺棱掉角]
    synonyms: [裂缝, 渗水, 空鼓, 麻面, 起砂, 露筋, 修补]
  防水与密封(质量通用):
    kind: quality
    labels: [卷材搭接不足, 涂膜厚度不足, 节点附加层缺失, 穿墙套管未封堵, 门窗周边渗漏]
    synonyms: [防水, 卷材, 涂膜, 搭接, 附加层, 密封, 止水环, 套管, 滴水线]
  保温与防腐(质量通用):
    kind: quality
    labels: [保温破损, 厚度不达标, 防腐漆道数不足, 金属件锈蚀, 冷凝结露]
    synonyms: [保温, 岩棉, XPS, 防腐, 环氧, 冷桥, 结露]
  装饰安装成品保护(质量通用):
    kind: quality
    labels: [成品未保护, 交叉作业污染/损坏, 线条/标高/垂直度超差, 缝格不均]
    synonyms: [成品保护, 交叉作业, 垂直度, 平整度, 缝格, 标高, 允许偏差]

  # =========================
  # 资料/过程控制（质量管理）
  # =========================
  资料与检验批(质量管理):
    kind: quality
    labels: [检验批资料缺失, 见证取样不齐, 原材料合格证缺失, 施工记录不全, 隐蔽工程未验收]
    synonyms: [资料, 检验批, 取样, 送检, 合格证, 记录, 隐蔽验收, 过程控制]
  试验与调试(质量管理):
    kind: quality
    labels: [混凝土试块不合格, 管道水压试验不合格, 风管漏风量超标, 电气绝缘与耐压不合格]
    synonyms: [试块, 试压, 漏风, 绝缘, 耐压, 调试, 联动, 试运行]

severity_rules:
  A（重大）：对人身安全/结构安全存在高概率严重后果或单点失效（如：临边无防护、深基坑支护失稳、电气带电可触达、起重严重违规、主要结构受力缺陷）。
  B（较大）：可能造成严重伤害/重大财产损失/系统性返工（如：模板体系重大缺陷、消防系统关键缺陷、接地防雷失效、强条不满足）。
  C（一般）：功能或耐久受影响、存在一般性返工风险（如：支吊架间距超差、装饰偏差、非关键节点做法不当）。
  D（低）：观察/改进项（如：标识不全、成品保护不足、资料不完善但可补齐）
risk_scoring:
  formula: "risk = likelihood * exposure * consequence * 4"
  bounds: [0, 100]
  defaults:
    likelihood: 3
    exposure: 3
    consequence: 3
  hints:
    高处/临边防护: {likelihood: 4-5, consequence: 4-5}
    电气安全: {likelihood: 3-4, consequence: 4-5}
kb:
  # 你的规范优先级（仅示例，按实际替换）
  priority: ["GB/国家标准", "AQ/安全生产行业标准", "行业/地方标准", "企业标准/作业指导书"]
  require_strict_clause: true
output_contract:
  bbox_norm: true
  fields_required: [scene_guess, auto_queries, hazards, kb_citations, severity, risk_score, confidence]
